name: Build and run all tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest]

    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:8})

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get and verify dependencies
        run: cd serverless-function && go mod download && go mod verify

      - name: Build webhooks handler to make sure there are zero issues
        run: cd serverless-function && cd cmd/ && go build -o webhooks-handler

      - name: Go vet
        run: cd serverless-function && go vet ./...

      - name: Run unit test
        run: cd serverless-function && go test ./...
